#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 VERSION ARM64_SHA256 X86_64_SHA256 OUTPUT" >&2
  exit 2
fi

version=$1
arm64_sha=$2
x86_64_sha=$3
output=$4

cat >"$output" <<EOF
# typed: strict
# frozen_string_literal: true

# This file is generated by deemson/shed release CI. DO NOT EDIT.
class Shed < Formula
  desc "Sync dotfiles between system paths and a local shed"
  homepage "https://github.com/deemson/shed"
  version "$version"
  license "MIT"

  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/deemson/shed/releases/download/v$version/shed-aarch64-apple-darwin.tar.gz"
    sha256 "$arm64_sha"
  else
    url "https://github.com/deemson/shed/releases/download/v$version/shed-x86_64-apple-darwin.tar.gz"
    sha256 "$x86_64_sha"
  end

  def install
    bin.install "shed"
  end

  test do
    assert_match "shed #{version}", shell_output("#{bin}/shed --version")
  end
end
EOF
